# Generated by Django 5.0.4 on 2026-05-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('locality', models.CharField(max_length=200, verbose_name='Localidad')),
                ('applicant', models.CharField(max_length=200, verbose_name='Aspirante')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
